# Site settings
title: An ordinary blog of software developer
email: undertext.2010@gmail.com
description: Posts about programming and related stuff
baseurl: ""
url: "https://undertext.github.io/"
twitter_username: undertextme
github_username:  undertext

disqus:
  shortname: undertext-github-io

google_analytics: UA-28621808-4

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
