# Site settings
title: An ordinary blog of an ordinary man
email: undertext.2010@gmail.com
description: Posts about programming and related stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://undertext.github.io/"
twitter_username: undertextme
github_username:  undertext

disqus:
  shortname: undertext-github-io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
